version: '3.3'

services:
  db:
    image: mysql:8.0.30-oracle
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - projectsqldata:/var/lib/mysql

  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: 
      context: ./deploy/phpfpm
    links:
      - db
    ports:
      - "9000:9000"
    environment:
      APPLICATION_ENV: ${APP_RUNTIME_ENV}
      APP_ENV: ${APP_ENV}
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:1.23.1-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./deploy/nginx/www.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  
  node:
    build:
      context: ./deploy/node
    ports:
      - "80:3000"
    links:
      - php
    # volumes:
      # - ./app:/app

volumes:
  projectsqldata:
    driver: "local"